require('dotenv').config();
const express = require('express');
const cors = require('cors');
const helmet = require('helmet');
const morgan = require('morgan');
const rateLimit = require('express-rate-limit');
const app = express();
app.use(helmet());
app.use(cors({origin:process.env.FRONTEND_URL||'*',methods:['GET','POST','PUT','DELETE'],allowedHeaders:['Content-Type','Authorization']}));
app.use(morgan('dev'));
app.use(express.json({limit:'1mb'}));
app.use(rateLimit({windowMs:15*60*1000,max:200,standardHeaders:true,legacyHeaders:false}));
app.use('/auth/login',rateLimit({windowMs:15*60*1000,max:20,message:{error:'Muitas tentativas'}}));
app.use('/auth',require('./routes/auth'));
app.use('/instances',require('./routes/instances'));
app.use('/keywords',require('./routes/keywords'));
app.use('/events',require('./routes/events'));
app.use('/webhook',function(r,s,n){require('./routes/webhook')(r,s,n)});
app.get('/health',(r,s)=>s.json({status:'ok',ts:new Date().toISOString()}));
app.use((r,s)=>s.status(404).json({error:'Not found'}));
app.use((e,r,s,n)=>{console.error(e);s.status(500).json({error:'Error'})});
const PORT=process.env.PORT||3000;
app.listen(PORT,()=>console.log('WA Signal porta '+PORT));